name: dartdoc_viewer
description: Dart API Reference
dependencies:
  browser: '>=0.10.0 <0.11.0'
  polymer: '>=0.15.0 <0.15.2'
  yaml: '>=0.9.0 <0.10.0'
dev_dependencies:
  barback: '>=0.11.0 <0.16.0'
  unittest: '>=0.10.0 <0.12.0'
transformers:
- polymer:
    entry_points: web/index.html
- dartdoc_viewer
