name: dartdoc_viewer
description: Dart API Reference
dependencies:
  browser: any
  polymer: any
  polymer_expressions: any
  yaml: any
dev_dependencies:
  barback: any
  unittest: any
transformers:
- polymer:
    entry_points: web/index.html
